const notFoundError = (res) =>
    res.status(404).send("Esta tarefa n√£o foi encontrada!");

module.exports = { notFoundError };
